/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Untitled.gltf -o src/components/PhoneModel.js 
*/

import React, { useEffect, useLayoutEffect, useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export default function PhoneModel({
  screenImage,
  screenMaterialName = "Material.001",
  ...props
}) {
  const { scene } = useGLTF("/models/Untitled.gltf");
  const screenTexture = useTexture(screenImage);
  const groupRef = useRef(null);

  const clonedScene = useMemo(() => {
    const clone = scene.clone(true);
    const materialCache = new Map();

    clone.traverse((child) => {
      if (!child.isMesh || !child.material) return;

      const materials = Array.isArray(child.material)
        ? child.material
        : [child.material];

      const nextMaterials = materials.map((material) => {
        if (!materialCache.has(material)) {
          const next = material.clone();

          if (next.map && next.map.colorSpace !== undefined) {
            next.map.colorSpace = THREE.SRGBColorSpace;
          }
          if (next.emissiveMap && next.emissiveMap.colorSpace !== undefined) {
            next.emissiveMap.colorSpace = THREE.SRGBColorSpace;
          }

          next.transparent = true;
          next.opacity = 1;
          next.depthWrite = false;
          next.needsUpdate = true;
          materialCache.set(material, next);
        }
        return materialCache.get(material);
      });

      child.material = Array.isArray(child.material)
        ? nextMaterials
        : nextMaterials[0];
      child.castShadow = false;
      child.receiveShadow = false;
    });

    return clone;
  }, [scene]);

  // Apply the screen texture
  useEffect(() => {
    if (!clonedScene || !screenTexture) return;

    // GLTF convention: textures should usually be flipY = false
    screenTexture.colorSpace = THREE.SRGBColorSpace;
    screenTexture.flipY = true;
    screenTexture.needsUpdate = true;

    clonedScene.traverse((child) => {
      if (!child.isMesh || !child.material) return;

      const materials = Array.isArray(child.material)
        ? child.material
        : [child.material];

      materials.forEach((material) => {
        if (material.name !== screenMaterialName) return;

        material.map = screenTexture;
        material.emissiveMap = screenTexture;
        material.emissive = new THREE.Color(0xffffff);
        material.emissiveIntensity = 0.7;
        material.toneMapped = false;
        material.needsUpdate = true;
      });
    });
  }, [clonedScene, screenMaterialName, screenTexture]);

  // Center the model
  useLayoutEffect(() => {
    if (!groupRef.current || !clonedScene) return;

    groupRef.current.updateWorldMatrix(true, true);
    const box = new THREE.Box3().setFromObject(clonedScene);
    const center = box.getCenter(new THREE.Vector3());

    groupRef.current.position.x -= center.x;
    groupRef.current.position.y -= center.y;
  }, [clonedScene]);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <primitive object={clonedScene} />
    </group>
  );
}

useGLTF.preload("/models/Untitled.gltf");
